version: '3.7'

services:
  be:
    image: ${IMAGE_NAME}
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/polyglot?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    networks:
      - backend

  db:
    build:
      context : .
      dockerfile: ./DockerfileMysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER : ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    networks:
      - backend

# Volumes
volumes:
  my-db:

networks:
  backend:
