name: polyglotci

on:
  push:
    branches:
      - "develop"
      - "game-3"
      - "fulvius31-game-3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Setup SSH
        env:
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        run:
          echo "$VPS_SSH_KEY" > ./private_key
          sudo apt-get install -y sshpass
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> known_hosts
      - 
        name: Deploy to VPS
        env:
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run:
          sudo chmod 600 ./private_key && ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=known_hosts -i ./private_key $VPS_USER@$VPS_HOST "cd /home/$VPS_USER/Polyglot && git pull && cd docker && docker-compose pull && docker-compose up --remove-orphans --force-recreate -d"
      - 
        name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build jar
        run: cd ./Back-End/slu-polyglot/ && ./gradlew build
      -
        name: Build and push springboot
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/polyglot-csci-5030-01-2023:testci
      -
        name: Build and push react
        uses: docker/build-push-action@v4
        with:
          context: ./Front-End/
          file: ./Front-End/DockerfileReact
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/polyglot-csci-5030-01-2023-fe:testci
